trigger:
  branches:
    include:
      - main  # Update if your branch is named differently

pool:
  name: 'SelfHostedPool'  # Replace with your self-hosted agent name; if using Microsoft-hosted, omit or set to 'Azure Pipelines'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.403'  # Change to the required .NET SDK version if necessary
  displayName: 'Install .NET SDK'

- script: |
    dotnet build --configuration Release
  displayName: 'Build ASP.NET Project'

- script: |
    dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Artifact'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
  displayName: 'Publish Artifact'
